### ISSUE TITLE
shock bug！

### ISSUE THREAD

**Issue by chujianzt** [shiyuwudi/yunfa_wiki#2]
人物传记--出差开除哥
已是链接形式但仍无法正常跳转，点击依然停留在Home页。。（莫不是把它给忘了）
求解决～

**Comment by shiyuwudi** [comment]
@chujianzt 已修复，补充了出差开除哥的描述，请查收。

**Comment by chujianzt** [comment]
验收通过，不过鉴于效率太慢，故而 两颗星⭐ ⭐
